### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by chaffinched** [skagr/footballdata#4]
Hi, interesting looking tool!

I'm getting an error similar to [nicoguaro's](https://github.com/skagr/footballdata/issues/3) on the example. Using footballdata installed via pip with Python3.6 I get **KeyError: 'premier-league_matches'** 
when running :
```
games = five38.read_games()
games.sample(5)
```
I do have FiveThirtyEight_1617.json in the data directory, and / or a renamed version for this year. Has too much changed on FiveThirtyEight for this to work, or did I break something?

**Comment by skagr** [comment]
I can't reproduce this. Did you use the json file from this repo?

fivethirtyeight.com did change the way they publish their data. As far as I can tell it is now embedded in obfuscated javascript. It would be possible to create a webscraper to get the data, but I haven't had time for this.

**Comment by chaffinched** [comment]
I'll have a play and see whether I get anywhere.
